// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxvc7GKlErjftV2WD4HGMx3Mq6lnvNT1o',
    appId: '1:349227748774:web:080a0ca626232c0e499367',
    messagingSenderId: '349227748774',
    projectId: 'artaku-finance-app',
    authDomain: 'artaku-finance-app.firebaseapp.com',
    storageBucket: 'artaku-finance-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWuSN7cCDqwM_dP7VZzvLSHEJxS_Z9kL8',
    appId: '1:349227748774:android:43bb97f1305fd203499367',
    messagingSenderId: '349227748774',
    projectId: 'artaku-finance-app',
    storageBucket: 'artaku-finance-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVSyF4vG0lePKYyijbzoZcSQbEsDEC6Q0',
    appId: '1:349227748774:ios:5c2ab80b4cd511c5499367',
    messagingSenderId: '349227748774',
    projectId: 'artaku-finance-app',
    storageBucket: 'artaku-finance-app.firebasestorage.app',
    iosBundleId: 'com.example.thriftlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVSyF4vG0lePKYyijbzoZcSQbEsDEC6Q0',
    appId: '1:349227748774:ios:5c2ab80b4cd511c5499367',
    messagingSenderId: '349227748774',
    projectId: 'artaku-finance-app',
    storageBucket: 'artaku-finance-app.firebasestorage.app',
    iosBundleId: 'com.example.thriftlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxvc7GKlErjftV2WD4HGMx3Mq6lnvNT1o',
    appId: '1:349227748774:web:22f8398772cb2271499367',
    messagingSenderId: '349227748774',
    projectId: 'artaku-finance-app',
    authDomain: 'artaku-finance-app.firebaseapp.com',
    storageBucket: 'artaku-finance-app.firebasestorage.app',
  );
}
